//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentLog.TrayLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Icons/merchant_16x16.ico")]
        public string TrayIconFile {
            get {
                return ((string)(this["TrayIconFile"]));
            }
            set {
                this["TrayIconFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Launcher Menu")]
        public string TrayToolTip {
            get {
                return ((string)(this["TrayToolTip"]));
            }
            set {
                this["TrayToolTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdatedExeSource {
            get {
                return ((string)(this["UpdatedExeSource"]));
            }
            set {
                this["UpdatedExeSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\__user_name_here__\\Google Drive\\__branch_name_here__\\TenantDBs")]
        public string DatabasesPath {
            get {
                return ((string)(this["DatabasesPath"]));
            }
            set {
                this["DatabasesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
""BaseURL""   : ""https://fortune-tenants.firebaseio.com/"",
""ApiKey""    : ""AIzaSyCQeia4H9rdzzYOsf_zfrjgnDvQsf04XZA"",
""Email""     : ""staff.pc-name@fortune.branch"",
""Password""  : ""firebase-password-here"",
""HumanName"" : ""Ms. MSA Staff"",
""Roles""     : ""Supervisor/Cashier""
}")]
        public string CredentialsKey {
            get {
                return ((string)(this["CredentialsKey"]));
            }
            set {
                this["CredentialsKey"] = value;
            }
        }
    }
}
